version: "3.9"
services:
  web:
    build:
      context: .
    container_name: django_backend_test
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=1
  db:
    image: postgres:13
    container_name: postgres_backend_test
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django_backend_test
volumes:
  postgres_data:
